services:
  postgres:
    image: postgres:18-alpine
    networks:
    - pg-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
    - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    networks:
      - pg-net
    
  app:
    build : .
    image: shortify:latest
    networks:
    - pg-net
    ports:
    - 8000:3000

volumes:
  postgres_data:
networks:
  pg-net: